baseURL = "/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Pragmatias Blog"
theme = "pragmatias"
Paginate = 5
copyright = "WTFPL license"

[permalinks]
	blog = "/:year/:month/:day/:title/"

[outputs]
	home = [ "HTML", "RSS" ]
	section = [ "HTML", "RSS" ] 
	taxonomy = [ "HTML", "RSS" ]


[outputFormats]
	[outputFormats.RSS]
  		mediatype = "application/rss"
  		baseName = "feed"


[taxonomies]
  tag = "tags"

[author]
    name = "pragmatias"

[[menus]]

	[[menu.global]]
		name = "Blog"
		weight = 5
		identifier = "blog"
		url = "/blog/"

	[[menu.global]]
		name = "Tags"
		weight = 10
		identifier = "tags"
		url = "/tags/"

	[[menu.global]]
		name = "Archives"
		weight = 15
		identifier = "archives"
		url = "/archives/"

[languages]
	[languages.fr]
    	weight = 10
    	languageName = "Français"
    	contentDir = "content/fr"
    	languageCode = "fr"
    	[languages.fr.params]
    	imagePNG = "france-flag-round-xs.png"

  [languages.en]
		weight = 20
		languageName = "English"
		contentDir = "content/en"
		languageCode = "en"
		[languages.en.params]
		imagePNG = "united-kingdom-flag-round-xs.png"

