baseURL = "https://www.pragmatias.fr"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Pragmatias Blog"
description = "Blog"
theme = "pragmatias"
Paginate = 5
copyright = "WTFPL license"
enableRobotsTXT = true

[permalinks]
	blog = "/:year/:month/:day/:title/"

[outputs]
	home = [ "HTML", "RSS" ]
	section = [ "HTML"] 
	taxonomy = [ "HTML"]
	term = [ "HTML"]


[outputFormats]
	[outputFormats.RSS]
  		mediatype = "application/rss"
  		baseName = "feed"


[taxonomies]
  tag = "tags"

[author]
    name = "pragmatias"
    email = "dev@pragmatias.fr"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[[menus]]
	[[menu.global]]
		name = "Blog"
		weight = 5
		identifier = "blog"
		url = "/blog/"

	[[menu.global]]
		name = "Tags"
		weight = 10
		identifier = "tags"
		url = "/tags/"

	[[menu.global]]
		name = "Archives"
		weight = 15
		identifier = "archives"
		url = "/archives/"

[languages]
  [languages.en]
		weight = 10
		languageName = "English"
		contentDir = "content/en"
		languageCode = "en"
		[languages.en.params]
		imagePNG = "united-kingdom-flag-round-xs-24.png"

	[languages.fr]
    	weight = 20
    	languageName = "Français"
    	contentDir = "content/fr"
    	languageCode = "fr"
    	[languages.fr.params]
    	imagePNG = "france-flag-round-xs-24.png"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    noClasses = false

