baseURL = "/"
languageCode = "en-us"
title = "Pragmatias Docs"
theme = "gohugoio_pragmatias"
paginate = 20

enableEmoji = true
defaultContentLanguage = "en"


#disableKinds = ["taxonomy", "taxonomyTerm"]
[taxonomies]
category = "categories"



[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "RSS"]


[params]
flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"


[params.blog]
title = "Pragmatias Blog"
description = "Just a life time ..."
