# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

dist: trusty
#language: go
#go:
#    - master

# before_install
# install - install any dependencies required

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo
    - echo 'pragmatias.fr' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  email: $GITHUB_EMAIL
#  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  repo: pragmatias/pragmatias.github.io
  target_branch: master  # branch contains blog content
  on:
    branch: master  # branch contains Hugo generator code