
######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES


  [[global]]
    name = "Blog"
    weight = 1
    identifier = "blog"
    url = "/blog/"

  [[global]]
    name = "Docs"
    weight = 5
    identifier = "docs"
    url = "/docs/"

  [[global]]
    name = "Contact"
    weight = 5
    identifier = "contact"
    url = "/contact/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "Nextcloud"
    weight = 150
    icon = true
    identifier = "nextcloud"
    post = "external"
    url = "https://pragmatias.synology.me/"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/pragmatias"

  [[global]]
    name = "Hugo"
    weight = 210
    identifier = "hugo"
    post = "external"
    url = "https://gohugo.io"



######## documentations menu


[[docs]]
  name = "General"
  weight = 1
  identifier = "general"
  url = "/docs/general/"
#  post = "break"

[[docs]]
  name = "Linux"
  weight = 5
  identifier = "linux"
  url = "/docs/linux/"
#  post = "break"

[[docs]]
  name = "Hadoop"
  weight = 15
  identifier = "hadoop"
  url = "/docs/hadoop/"
#  post = "break"

[[docs]]
  name = "Teradata"
  weight = 20
  identifier = "teradata"
  url = "/docs/teradata/"
#  post = "break"



